### ISSUE TITLE
GRM - contour and contourf seem to be displaced

### ISSUE THREAD

**Issue by mantielero** [sciapp/gr#117]
It looks like the plot is displaced to the bottom left (or that image is clipped in the top and the right). You can see the effect [here](https://mantielero.github.io/gr.nim/contour/) and [here](https://mantielero.github.io/gr.nim/contourf/).

**Comment by IngoMeyer441** [comment]
The example image was probably generated with GR v0.48.0 (the latest version uses another font)?
With our current version I get a correctly positioned image with similar C code:
![image](https://user-images.githubusercontent.com/1449087/80972131-060e8780-8e1e-11ea-8943-a19e618f00c6.png)

**Comment by IngoMeyer441** [comment]
Contour plot:

![image](https://user-images.githubusercontent.com/1449087/80972686-b41a3180-8e1e-11ea-8b07-b4c9e99274d2.png)

**Comment by mantielero** [comment]
Even in your examples it can be seen that something funny is happenning. In the first picture, it looks like the contain is displaced to the right. 
In the second one, it looks like there is some clipping at the bottom and the top, but not on the left and the right. It looks like the major ticks where drawing white rectangle on top of the figure.
I have updated to 0.49, and I get the attached figures.

On the other hand, you can see in the following pictures (by me, using 0.49) that it looks like the clipping is on the right and on top.
![contour_v0 49 0](https://user-images.githubusercontent.com/1116064/80995993-69f57800-8e3f-11ea-8983-db15a4a6babd.png)
![contourf_v0 49](https://user-images.githubusercontent.com/1116064/80996001-6d88ff00-8e3f-11ea-8791-0ecd95a1de62.png)

**Comment by IngoMeyer441** [comment]
The input data for `x` and `y` are random numbers between -4 and 4. But in most cases the numbers -4 and 4 are not chosen by the random number generator (you only get slightly larger and smaller values). The `contour` and `contourf` functions use the actual input minimum and maximum but GRM rounds minimum and maximum to the nearest integer when drawing the coordinate system which is the reason for the white border and why it changes for every program run.
So, the result you get is actually correct. But of course, the white border is quite disturbing. In order to remove it you can set `adjust_xlim` and `adjust_ylim` to `0`:

![image](https://user-images.githubusercontent.com/1449087/81043934-8e8b3780-8eb3-11ea-93a4-10367d06131b.png)

**Comment by mantielero** [comment]
Understood. Thanks a lot.
