### ISSUE TITLE
Tilde in Plots using GR as backend

### ISSUE THREAD

**Issue by airglide** [sciapp/gr#126]
Hello

I tried to use the GR backend with Plots to label the axis, the tilde is misplaced, it should be above the x

Code to reproduce problem:
```
using Plots

gr()
Plots.GRBackend()
plot([0,1],[2,2])
ylabel!("\$\\tilde{x}\$")
```
the output looks like:
![plt](https://user-images.githubusercontent.com/1805145/87152756-92be4180-c2b6-11ea-8171-9b3479e78152.png)

I looked at the temp file generated by the latex and this looks fine, not sure if the problem comes maybe from Plots.jl, I tried to recreate the problem with Plotly and had no issue there so I figured I post it here.

**Comment by FlorianRhiem** [comment]
Hello, thank you for reporting this.

The bearing of the combining tilde and similar characters was being applied in the wrong direction, moving it away from the x instead of back above it. I've [fixed it in develop](https://github.com/sciapp/gr/commit/3da94edcd371c6d5d65d819d1e4ff57e009d4362) and the fix will be part of the next release.
