### ISSUE TITLE
openSUSE build service and Ruby

### ISSUE THREAD

**Issue by bkmgit** [sciapp/gr#142]
Fedora build on openSUSE build service seems not to be fully functional. The following example

```ruby
require 'gr/plot'

x  = Numo::DFloat.linspace(0, 10, 101)
y1 = Numo::NMath.sin(x)
y2 = Numo::NMath.cos(x)

GR.plot(
  [x, y1, 'bo'], [x, y2, 'g*'],
  title:    "Multiple plot example",
  xlabel:   "x",
  ylabel:   "y",
  ylim:     [-1.2, 1.2],
  labels:   ["sin(x)", "cos(x)"],
  location: 11
)

GR.savefig("figure.png")
```

works with a self compiled GR installation on Fedora. However, it does not work with the Fedora build from openSUSE build service.  The example at https://github.com/sciapp/gr/blob/master/examples/griddata.c does compile with both.

**Comment by bkmgit** [comment]
Seems to work following https://github.com/red-data-tools/GR.rb/pull/53 slightly different export variables needed.

**Comment by kojix2** [comment]
Hi gr developers!

To be honest, I wasn't aware that the sciapp/gr package was distributed with the openSUSE build service until @bkmgit pointed it out. Currently, Red-data-tools distributes its own gr package, but we would like to stop distributing it in the future.

However, I tried to add the openSUSE build service repository to my local Ubuntu computer, but it didn't work with some key error.
Also, GR.rb is using pkg-config to find shared libraries, but that doesn't seem to be working either. I think it's because it can't find the ".pc" file.

I am still trying to resolve this issue. If I have any more problems I will report them to sciapp/gr.

Thank you very much.

**Comment by IngoMeyer441** [comment]
Perhaps @cfelder knows more about these problems.

**Comment by cfelder** [comment]
Unfortunately the DSA1024 key inherited from the parent project science is still valid, but considered too weak by some distributions. I pointed this out by mail and bug trackers to the OBS maintainers in 2018. unfortunately the key still has not upgraded yet. You can workaround this by manually declaring the repository as trusted.

I am currently on vacation. may  I can ping the OBS folks again once I‘m back.

Regarding the paths for libraries and so on we used to have a common prefix (grdir) in the past. I agree that for packaged versions it would make sense to change that to point to well used paths lib(64), share, ... . This would require changes in various wrappers, python, julia, and probably your ruby code.

As far as I can see you already figured out how to „fix“ your ruby wrapper. We should keep you in line when applying changes to this part.

I hope this sheds some light on this.

Best
Christian

**Comment by kojix2** [comment]
Any progress on this issue?
