### ISSUE TITLE
GKSterm on macOS Mojave will not open 'save as' dialog

### ISSUE THREAD

**Issue by jamie-arcc** [sciapp/gr#84]
I am using GR v0.40.0 installed via Julia.  I am using it as a backend for Plots.jl via GR.jl on macOS Mojave 10.14.5.  After the plot is generated and GKSterm opens, I am unable to save the image.  using either File>Save As or ⌘⇧S, the 'Save As' dialog never opens

**Comment by FlorianRhiem** [comment]
Thank you for reporting this issue, I've fixed the "Save As..." dialog in 17c16e778bbc6dc11acca82635f258f8df4ebba8.

As a side note, depending on what kind of output you need, it might be better to use a different [workstation type](https://gr-framework.org/workstations.html) instead of relying on the save function in GKSTerm, e.g. you could use `GKS_WSTYPE=png` or use `gr_beginprint("output.png")`.
