### ISSUE TITLE
There might be some confusion about gr_cellarray and gks_cellarray ?

### ISSUE THREAD

**Issue by kojix2** [sciapp/gr#91]
Hello.
I'm new to gr-framework.
I doubt that something is wrong with `gr_cellarray` and `gks_cellarray`.

gr.c
https://github.com/sciapp/gr/blob/494f193a9120957cb85222727260da2de70682f2/lib/gr/gr.c#L1720-L1723

https://github.com/sciapp/gr/blob/494f193a9120957cb85222727260da2de70682f2/lib/gr/gr.c#L1734

https://github.com/sciapp/gr/blob/494f193a9120957cb85222727260da2de70682f2/lib/gr/gr.c#L1739

working example
https://github.com/sciapp/gr/issues/39#issuecomment-301684973
>   gr_cellarray(-0.5, 3.5, 3.5, -0.5, 4, 4, 1, 1, 4, 4, colia);

The direction of the Y axis may be opposite for gr and gks. 
Even so, it seems somehow inconsistent.

I'm sorry if I'm wrong.

**Comment by FlorianRhiem** [comment]
Hello,
the `gr_` and `gks_` sets of functions are for two libraries with different aims:
- libGKS is our implementation of the graphical kernel system (GKS) ISO standard, with some extensions. It provides comparatively low-level drawing of 2D primitives with a collection of drivers and plugins to support various output formats.
- libGR on the other hand is significantly higher-level and provides functions like drawing axes, where libGKS only provides functions to draw text and lines instead of complete axes. With libGR the aim is to provide a convenient API with functionality built on top of libGKS.

As a result, there are a few cases where the APIs may look *very* similar but may behave differently. In general, I would recommend sticking to the gr API for your code.

**Comment by kojix2** [comment]
Thank you @FlorianRhiem.

I use GR modules from Ruby and Julia. I don't use GKS.
But look at the example below.

https://github.com/sciapp/gr/issues/39
> gr_cellarray(-0.5, 3.5, 3.5, -0.5, 4, 4, 1, 1, 4, 4, colia);

ymin is greater than ymax. Isn't this a little strange?

**Comment by FlorianRhiem** [comment]
Not really, in this case the top row of the image is positioned at -0.5 and the bottom row is positioned at 3.5, which means that the image will appear upside-down. I think this was the aim in the example.
Alternatively you could reverse the image rows themselves instead of swapping ymin and ymax.

**Comment by kojix2** [comment]
Hmm. I still don't understand.
I feel something is wrong.

![image](https://user-images.githubusercontent.com/5798442/65673945-bb0de400-e086-11e9-83f2-04e7ca4db81e.png)

![image](https://user-images.githubusercontent.com/5798442/65674013-d973df80-e086-11e9-8ea5-3696d08d6374.png)

**Comment by FlorianRhiem** [comment]
I think the problem there is that you're trying to draw a cellarray between xmin=-0.5 and xmax=-0.5, so it would have a width of 0 and would be invisible.

**Comment by kojix2** [comment]
I see. Now I understand.
Sorry for the trouble you.
Thank you.
